// Reference values the AI uses to estimate "describe your meal" entries.
// Users never browse this list — it just keeps the AI's numbers realistic,
// especially for Iranian dishes that generic models guess badly.
// Values are approximate, per ONE household unit.

module.exports = [
  // ── Iranian mains ──
  { name:'Kabab koobideh',        fa:'کباب کوبیده',     unit:'skewer',  protein:15, calories:230 },
  { name:'Joojeh kabab',          fa:'جوجه کباب',       unit:'skewer',  protein:30, calories:250 },
  { name:'Kabab barg',            fa:'کباب برگ',        unit:'skewer',  protein:32, calories:280 },
  { name:'Kabab soltani',         fa:'کباب سلطانی',     unit:'serving', protein:47, calories:510 },
  { name:'Jigar (liver kabab)',   fa:'جگر',             unit:'skewer',  protein:18, calories:140 },
  { name:'Ghormeh sabzi',         fa:'قورمه سبزی',      unit:'serving', protein:20, calories:330 },
  { name:'Gheymeh',               fa:'قیمه',            unit:'serving', protein:18, calories:360 },
  { name:'Fesenjan (chicken)',    fa:'فسنجان',          unit:'serving', protein:25, calories:480 },
  { name:'Khoresh bademjan',      fa:'خورش بادمجان',    unit:'serving', protein:18, calories:350 },
  { name:'Khoresh karafs',        fa:'خورش کرفس',       unit:'serving', protein:17, calories:280 },
  { name:'Zereshk polo ba morgh', fa:'زرشک پلو با مرغ', unit:'plate',   protein:38, calories:650 },
  { name:'Baghali polo ba mahiche', fa:'باقالی پلو با ماهیچه', unit:'plate', protein:42, calories:780 },
  { name:'Adas polo',             fa:'عدس پلو',         unit:'plate',   protein:15, calories:520 },
  { name:'Loobia polo',           fa:'لوبیا پلو',       unit:'plate',   protein:22, calories:600 },
  { name:'Tahchin',               fa:'ته چین',          unit:'serving', protein:25, calories:560 },
  { name:'Abgoosht / Dizi',       fa:'آبگوشت',          unit:'serving', protein:30, calories:600 },
  { name:'Kotlet',                fa:'کتلت',            unit:'piece',   protein:8,  calories:150 },
  { name:'Kuku sabzi',            fa:'کوکو سبزی',       unit:'piece',   protein:7,  calories:140 },
  { name:'Kuku sibzamini',        fa:'کوکو سیب زمینی',  unit:'piece',   protein:4,  calories:160 },
  { name:'Olivieh sandwich',      fa:'ساندویچ الویه',   unit:'sandwich',protein:15, calories:450 },
  { name:'Kashk bademjan',        fa:'کشک بادمجان',     unit:'serving', protein:8,  calories:250 },
  { name:'Mirza ghasemi',         fa:'میرزا قاسمی',     unit:'serving', protein:8,  calories:200 },
  { name:'Dolmeh',                fa:'دلمه',            unit:'piece',   protein:2,  calories:60 },
  { name:'Ash reshteh',           fa:'آش رشته',         unit:'bowl',    protein:10, calories:300 },
  { name:'Adasi',                 fa:'عدسی',            unit:'bowl',    protein:12, calories:230 },
  { name:'Haleem',                fa:'حلیم',            unit:'bowl',    protein:15, calories:350 },
  { name:'Kaleh pacheh',          fa:'کله پاچه',        unit:'serving', protein:30, calories:500 },
  { name:'Omelette (Iranian, tomato)', fa:'املت',        unit:'serving', protein:13, calories:250 },
  { name:'Chelo (plain rice)',    fa:'برنج / چلو',      unit:'plate',   protein:6,  calories:350 },

  // ── Iranian breads & breakfast ──
  { name:'Sangak bread',          fa:'نان سنگک',        unit:'piece',   protein:9,  calories:260 },
  { name:'Barbari bread',         fa:'نان بربری',       unit:'piece',   protein:8,  calories:250 },
  { name:'Lavash bread',          fa:'نان لواش',        unit:'sheet',   protein:3,  calories:90 },
  { name:'Taftoon bread',         fa:'نان تافتون',      unit:'piece',   protein:5,  calories:170 },
  { name:'Panir (white cheese)',  fa:'پنیر',            unit:'piece',   protein:5,  calories:80 },
  { name:'Mast (plain yogurt)',   fa:'ماست',            unit:'bowl',    protein:6,  calories:100 },
  { name:'Doogh',                 fa:'دوغ',             unit:'glass',   protein:5,  calories:60 },
  { name:'Walnuts',               fa:'گردو',            unit:'handful', protein:4,  calories:185 },

  // ── Common foods ──
  { name:'Egg',                   fa:'تخم مرغ',         unit:'egg',     protein:6,  calories:75 },
  { name:'Chicken breast',        fa:'سینه مرغ',        unit:'palm',    protein:30, calories:165 },
  { name:'Beef steak',            fa:'استیک',           unit:'palm',    protein:28, calories:250 },
  { name:'Salmon fillet',         fa:'ماهی سالمون',     unit:'fillet',  protein:25, calories:280 },
  { name:'Tuna (canned)',         fa:'تن ماهی',         unit:'can',     protein:25, calories:110 },
  { name:'Greek yogurt',          fa:'ماست یونانی',     unit:'cup',     protein:17, calories:130 },
  { name:'Cottage cheese',        fa:'پنیر کاتیج',      unit:'cup',     protein:25, calories:200 },
  { name:'Milk',                  fa:'شیر',             unit:'glass',   protein:8,  calories:120 },
  { name:'Whey protein shake',    fa:'شیک پروتئین',     unit:'scoop',   protein:24, calories:120 },
  { name:'Lentils (cooked)',      fa:'عدس',             unit:'cup',     protein:18, calories:230 },
  { name:'Chickpeas (cooked)',    fa:'نخود',            unit:'cup',     protein:15, calories:270 },
  { name:'Pasta (cooked)',        fa:'ماکارونی',        unit:'plate',   protein:10, calories:400 },
  { name:'Pizza',                 fa:'پیتزا',           unit:'slice',   protein:12, calories:285 },
  { name:'Burger',                fa:'همبرگر',          unit:'burger',  protein:25, calories:500 },
  { name:'Toast / sliced bread',  fa:'نان تست',         unit:'slice',   protein:3,  calories:80 },
  { name:'Vegetables / salad',    fa:'سبزیجات / سالاد', unit:'bowl',    protein:2,  calories:50 },
];
